name: CI/CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install 
        run: |
          npm install  
          cd frontend
          npm install
          cd ..
      - name: lint
        run: npm run lint
      - name: build frontend
        run: npm run build:frontend
      - name: ls
        run: | 
          ls -la
          cd build
          ls -la
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phonebook911" 
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "build"
          healthcheck: "https://phonebook911.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
        env:
          HD_MONGODB_URI: ${{secrets.MONGODB_URI}}

